"""rename user_id to employee_id in notification

Revision ID: 09012127fde6
Revises: 2ff83016f70b
Create Date: 2025-05-21 12:50:44.139717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09012127fde6'
down_revision: Union[str, None] = '2ff83016f70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint('notification_user_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'employee', ['employee_id'], ['id'])
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_user_id_fkey', 'notification', 'employee', ['user_id'], ['id'])
    op.drop_column('notification', 'employee_id')
    # ### end Alembic commands ###
