"""Initial migration

Revision ID: 2ff83016f70b
Revises: 5fd7ee6b12b7
Create Date: 2025-05-21 12:48:13.821975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff83016f70b'
down_revision: Union[str, None] = '5fd7ee6b12b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('task_id', sa.Integer(), nullable=True))
    op.alter_column('notification', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notification', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    op.create_foreign_key(None, 'notification', 'task', ['task_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'employee', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.alter_column('notification', 'message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('notification', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notification', 'task_id')
    # ### end Alembic commands ###
