"""Convert date column to Date type

Revision ID: 3356e7abe13f
Revises: a76ea538e605
Create Date: 2025-04-06 03:41:08.104588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3356e7abe13f'
down_revision: Union[str, None] = 'a76ea538e605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE task ALTER COLUMN date TYPE DATE USING date::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'date', type_=sa.String(50))
    # ### end Alembic commands ###
