"""Add notification_type column

Revision ID: 3bf55f2c3323
Revises: 0bf6fb66961a
Create Date: 2025-05-21 17:07:26.903037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf55f2c3323'
down_revision: Union[str, None] = '0bf6fb66961a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notification_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'notification_type')
    # ### end Alembic commands ###
