"""Add manager_id to Employee

Revision ID: 4342cc1e64bd
Revises: ec741eca3c15
Create Date: 2025-04-28 13:26:50.517462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4342cc1e64bd'
down_revision: Union[str, None] = 'ec741eca3c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'employee', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'manager_id')
    # ### end Alembic commands ###
