"""Initial migration

Revision ID: 5fd7ee6b12b7
Revises: 959410bbf8f2
Create Date: 2025-05-17 19:41:43.947499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd7ee6b12b7'
down_revision: Union[str, None] = '959410bbf8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('department_manager_id_fkey', 'department', type_='foreignkey')
    op.drop_column('department', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('department_manager_id_fkey', 'department', 'employee', ['manager_id'], ['id'])
    # ### end Alembic commands ###
