"""Add is_ceo and is_manager fields

Revision ID: 61fbd45918cf
Revises: f8804eabcf49
Create Date: 2025-05-24 12:24:23.678533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61fbd45918cf'
down_revision: Union[str, None] = 'f8804eabcf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_manager', sa.Boolean(), nullable=True))
    op.add_column('employee', sa.Column('is_ceo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_ceo')
    op.drop_column('employee', 'is_manager')
    # ### end Alembic commands ###
