"""Initial migration

Revision ID: 959410bbf8f2
Revises: a912af0ae4bf
Create Date: 2025-05-17 19:03:10.028412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959410bbf8f2'
down_revision: Union[str, None] = 'a912af0ae4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'department', 'employee', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'manager_id')
    # ### end Alembic commands ###
