"""Add email, phone, job_title to Employee

Revision ID: c0fa78339215
Revises: 6a263d6e908a
Create Date: 2025-05-05 11:40:10.697668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fa78339215'
down_revision: Union[str, None] = '6a263d6e908a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'employee', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###
