"""Add archived_at column to archived_task

Revision ID: cd9cea4a313b
Revises: 372ed41e34d0
Create Date: 2025-05-25 10:10:54.752305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9cea4a313b'
down_revision: Union[str, None] = '372ed41e34d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_task', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archived_task', 'archived_at')
    # ### end Alembic commands ###
