"""Initial migration

Revision ID: e2bef6893cc3
Revises: 
Create Date: 2025-04-05 13:38:23.966225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bef6893cc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('employee', 'position')
    op.drop_column('employee', 'phone')
    op.drop_column('employee', 'email')
    op.add_column('task', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'employee_id')
    op.add_column('employee', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('employee', 'password')
    # ### end Alembic commands ###
