"""New Style New theme and tags

Revision ID: f8804eabcf49
Revises: 3bf55f2c3323
Create Date: 2025-05-24 01:06:16.194875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8804eabcf49'
down_revision: Union[str, None] = '3bf55f2c3323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'notification_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
